name: User Story
description: Template for creating user stories
title: "[STORY]"
labels: ['type: :book: user story']
assignees: []
projects: []
body:
- type: textarea  
  id: story
  attributes:
    label: User Story
    value: |      
      As a [type of user],
      I want [a goal]
      So that [benefit].
  validations:
    required: true
- type: textarea  
  id: ac
  attributes:
    label: Acceptance Criteria
    description: "A list of required criteria to consider this story has been achieved"
    placeholder: |
      - [ ] Criteria 1
      - [ ] Criteria 2
      - [ ] ...
- type: textarea  
  id: info
  attributes:
    label: Additional information
    description: "Add any additional context, requirements, or notes related to the user story."
